
spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
springdoc:
  swagger-ui:
    path: swagger-ui.html
    operations-sorter: method
server:
  port: 8088
  servlet:
    context-path: /jira/api
